.githooks/pre-commit
Dear `kDrive Desktop` developers, to activate the proposed pre-commit hook, please run this command in your local git repository: 
```
$ git config --lobal core.hookspath .githooks
```
=> Adds a pre-commit git hook to automatically format staged files with clang-format

.gitignore, src/gui/parametersdialog.cpp
This change removes the hard-coded value of `100 GB` mentioned in an error message, as envisioned in the issue [KDESKTOP-580](https://infomaniak.atlassian.net/browse/KDESKTOP-580).
This limit may change with the back-end server characteristics and we have no actual means to retrieve the information at the moment.
[KDESKTOP-580]: https://infomaniak.atlassian.net/browse/KDESKTOP-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KDESKTOP-580] Removes reference to an explicit size limit for uploaded files

.gitignore, infomaniak-build-tools/linux/Readme.md, infomaniak-build-tools/macos/Readme.md, infomaniak-build-tools/windows/Readme.md, src/gui/CMakeLists.txt, src/gui/abstractfileitemwidget.cpp, src/gui/genericerroritemwidget.cpp, src/gui/genericerroritemwidget.h, src/gui/guiutility.cpp, src/gui/parametersdialog.cpp, src/libcommonserver/CMakeLists.txt, src/libsyncengine/propagation/executor/executorworker.cpp, src/libsyncengine/propagation/executor/executorworker.h, test/libparms/CMakeLists.txt, uninstaller/MacOSX/kDriveUninstaller/kDriveUninstaller.xcodeproj/project.pbxproj, uninstaller/MacOSX/kDriveUninstaller/kDriveUninstaller.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, uninstaller/MacOSX/kDriveUninstaller/kDriveUninstaller.xcodeproj/xcshareddata/xcschemes/kDrive Uninstaller.xcscheme
Link in error item widget where badly formatted and opened in the execution folder instead of in the sync folder
=> KDESKTOP-394 Fix path in error widget

src/libsyncengine/update_detection/file_system_observer/localfilesystemobserverworker.cpp
This pull-request addresses the issue [DESKTOP-31](https://infomaniak.atlassian.net/browse/KDESKTOP-31) : 
- The log level when logging the found items in the full item list parsed within `LocalFileSystemObserverWorker::exploreDir`, is now set to `DEBUG`.
- These logs are only recorded in the extended log of the application (i.e., only if the user checked the extended log box in her preferences).
=> [KDESKTOP-31] Change the logging level of verbose item lists in `LocalFileSystemObserverWorker::exploreDir`

src/gui/appclient.cpp, src/gui/clientgui.cpp, src/gui/clientgui.h, src/gui/debuggingdialog.cpp
This pull request addresses [KDESKTOP-240](https://infomaniak.atlassian.net/browse/KDESKTOP-240): the delay to purge logs is raised from 24 hours to 7 days if the user checks the corresponding preference box.
[KDESKTOP-240]: https://infomaniak.atlassian.net/browse/KDESKTOP-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KDESKTOP-240] Delete user logs only after 7 days

src/libsyncengine/jobs/jobmanager.h, test/libsyncengine/jobs/testjobmanager.cpp, test/libsyncengine/jobs/testjobmanager.h
The goal of this is just to add a test that show that sockets remain connected as long as Poco's HTTPSClientSession remain valid
=> KDESKTOP-468-POC-reuse-socket

src/libsyncengine/propagation/executor/executorworker.cpp
This case is already correctly handled:
`2024-04-12 10:42:05:125 [D] (0x700007ca2000) executorworker.cpp:614 - *1* File /Users/clementkunz/kDrive/Test.txt already exists on local replica`
But the description was incomplete, the PR just add more explanation in comment
=> KDESKTOP-94-Sync-loop-because-of-case-issue

src/libsyncengine/reconciliation/platform_inconsistency_checker/platforminconsistencycheckerworker.cpp, src/libsyncengine/reconciliation/platform_inconsistency_checker/platforminconsistencycheckerworker.h
Following [issue](https://infomaniak.atlassian.net/browse/KDESKTOP-393) the local items that were blacklisted remains in the update tree. This should not be the case, no excluded items should appear in the update tree.
=> KDESKTOP-684-Operation-generator-fail-if-an-item-with-DELETE-operation-is-blacklisted

src/libsyncengine/propagation/executor/executorworker.cpp
REbuild the local snapshot when there is too many propagated changes, regardless of the target side
=> KDESKTOP-753-Some-local-changes-not-propagated

src/gui/abstractfileitemwidget.cpp, src/gui/adddriveconfirmationwidget.cpp, src/gui/adddriveconfirmationwidget.h, src/gui/genericerroritemwidget.cpp, src/gui/guiutility.cpp, src/gui/guiutility.h, src/libsyncengine/jobs/network/downloadjob.cpp
This bug has been detected on MacOSX, but should be visible on every operaring system: the method `QFileInfo:path()` removes the name of the item from its output path, see https://doc.qt.io/qt-6/qfileinfo.html#path.
=> [HOTFIX] Open local folder of a new drive instead of its parent 

src/libsyncengine/requests/serverrequests.cpp
Conflict errors remained in the error list even when the conflict was already resolved.
=> KDESKTOP-776 - Fix error cleaning

src/server/vfs/win/vfs_win.cpp
The pinstate of pinned folder on Windows was changed after each app startup. This behavior seems to be caused by the fact that the pinstate "ONLINE" was set recursively on the root folder at each startup.
=> KDESKTOP-784 - Do not set pinstate to "Online" at each startup

src/gui/appclient.cpp, src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp, src/server/appserver.cpp
Do not send information message to sentry anymore.
=> KDESKTOP-751-Remove-sentry-message-just-keep-errors

translations/client_de.ts, translations/client_es.ts, translations/client_fr.ts, translations/client_it.ts
The text for synchronizations removal is oversized and doesn't fit with the containing button size:
This pull-request suggests shorter texts for the three supported languages distinct from english.
=> [KDESKTOP-801]  Shortens translations of 'Remove all synchronizations' 

src/server/appserver.cpp, src/server/appserver.h
This pull request addresses the bug reported in [KDESKTOP-795](https://infomaniak.atlassian.net/browse/KDESKTOP-795).
[KDESKTOP-795]: https://infomaniak.atlassian.net/browse/KDESKTOP-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KDESKTOP-795] Restores proper deletion of a drive with no synchronizations

src/libsyncengine/jobs/network/abstractnetworkjob.cpp, src/libsyncengine/jobs/network/abstractnetworkjob.h, src/libsyncengine/propagation/executor/executorworker.cpp, src/libsyncengine/propagation/executor/executorworker.h
This issue was a side effect of a fix aiming to ignore errors 404 on dowload jobs because is not available anymore on storage.
However, the this case, a directory has been deleted while we were trying to propagate a move operation inside it. The reaction to the error 404 must be different in this case : simply rebuild the snapshot and restart the sync.
=> KDESKTOP-804-Incorrect-resolution-of-the-MoveParentDelete-conflict-for-folders

src/server/appserver.cpp
The auto start parameter should be activated by default
=> KDESKTOP-408-Launch-at-startup-on-macOS

src/libcommonserver/io/iohelper.h, src/libcommonserver/io/iohelper_win.cpp, test/libcommonserver/io/testchecksetgetrights.cpp
From Microsoft documentation:
> https://learn.microsoft.com/en-us/windows/win32/api/aclapi/nf-aclapi-geteffectiverightsfromacla
> 
> The GetEffectiveRightsFromAcl function fails and returns ERROR_INVALID_ACL if the specified ACL contains an inherited access-denied ACE.
From my personal test on Windows 11 Pro 23H2, the function does work as expected and returns the rights for the trustee even if the ACL contains an inherited access-denied ACE.
If we get ERROR_INVALID_ACL, we will consider to be in the case described in the documentation and consider the file as not existing (we can't get the rights).
This PR also add tests for inherited permission and for files/folders on without inherited permission. 
To test inheritance, I introduced `IoHelper::_setRightsWindowsApiInheritance`, which is …
=> Kdesktop 849 add tests and documentation for get rights

src/server/appserver.cpp
Multiple entries of kDrive.app appeared in the "Open at login" preference panel of macOS
=> KDESKTOP-863-Do-not-setup-auto-start-in-debug-mode

src/libsyncengine/jobs/network/deletejob.cpp, src/libsyncengine/jobs/network/deletejob.h, src/libsyncengine/propagation/executor/executorworker.cpp, src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp, test/libsyncengine/jobs/network/testnetworkjobs.cpp, test/libsyncengine/jobs/testjobmanager.cpp, test/libsyncengine/propagation/executor/testintegration.cpp, test/libsyncengine/update_detection/file_system_observer/testremotefilesystemobserverworker.cpp
IoHelper::checkIfPathExistsWithSameNodeId was called with the remote ID while it should have been called with local ID
=> KDESKTOP-922 - Fix call to IoHelper::checkIfPathExistsWithSameNodeId in delete job

src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp
This PR remove a functionnality added in version 3.6.0.
The feature was waiting for a big file to be completly copied before starting to sync it.
However, we notice that this would make the sync of Office files (among others) impossible while the file is open in Word or similar apps.
=> KDESKTOP-919 - Do not check file availability for syncing it for now

infomaniak-build-tools/linux/Readme.md, infomaniak-build-tools/macos/Readme.md, infomaniak-build-tools/windows/Readme.md
In order to avoid copying the lib by hand in debug mode, we need to add an environment variable pointing to the lib folder. For example on macOS : `/usr/local/lib`.
Doc updated
=> Add environment variable pointing to the local lib folder

infomaniak-build-tools/linux/Readme.md
Some `std::` functions, such as `std::format`, are not available in the current version of libc++.
Certain standard functions from the C++ library (e.g., `std::format`) are missing in the current version of libc++ we are using. This issue is specific to MacOS and Ubuntu environments.
The missing functions seem to be implemented starting from Xcode 15.3. More information can be found in the [C++ Language Support section on the Apple Developer site](https://developer.apple.com/documentation/xcode/c++-language-support).
These functions are supported starting from CLang 17. Reference: [Compiler support for C++20 on cppreference.com](https://en.cppreference.com/w/cpp/compiler_support).
No changes are required.
- Upgrade the development environment on MacOS to Xcode 15.3 or later.
- Upgrade …
=> KDESKTOP-966-Bump-Xcode-Clang

.github/workflows/windows.yml, infomaniak-build-tools/run-tests.ps1
Unit tests are failing to run on Windows. The tests are not executing on the CI system. It appears that the paths are incorrect, leading to failures when attempting to execute the different test executables (text.exe). Additionally, the CI does not catch these errors and does not fail in such cases. This issue needs to be addressed within the scope of this PR.
=> KDESKTOP-981 Unit tests failing to run on Windows and CI not catching errors.

src/gui/adddriveslitesyncwidget.cpp
This pull-request restores the original format of an information label displayed when creating a drive:
The string formatting was broken due to a misuse of the raw string `R` instruction. 
With the proposed changes, the offending string is displayed as above.
=> [HOTFIX] Fixes label string with incorrect formatting inside the AddDriveLiteSyncWidget

src/libsyncengine/update_detection/file_system_observer/remotefilesystemobserverworker.cpp, src/libsyncengine/update_detection/file_system_observer/remotefilesystemobserverworker.h
The crash was introduced following a small refactoring suggested by SonarCloud.
It crashed while processing the event on files retrieved from the back through the '/listing/continue' request
=> KDESKTOP-988-Crash-on-Windows-invalid-comparator

src/libsyncengine/update_detection/file_system_observer/localfilesystemobserverworker.cpp, test/libsyncengine/update_detection/file_system_observer/testlocalfilesystemobserverworker.cpp, test/libsyncengine/update_detection/file_system_observer/testlocalfilesystemobserverworker.h, test/test_utility/temporarydirectory.cpp, test/test_utility/temporarydirectory.h
The re-activation of the LFSO unit tests would have prevented a regression.
However, the latter task is more involved than expected: after a first refactoring proposed in this pull request, a number of assertions fail with no clear reason.
To be continued with https://infomaniak.atlassian.net/browse/KDESKTOP-990.
=> [HOTFIX] Revert the accidental merge of two if-statements

src/libsyncengine/reconciliation/conflict_resolver/conflictresolverworker.cpp, src/libsyncengine/reconciliation/conflict_resolver/conflictresolverworker.h, src/libsyncengine/update_detection/update_detector/node.h
This pull request only removes some unused calls and variables.
These changes are likely to solve the infinite loop issue described in [KDESKTOP-1045](https://infomaniak.atlassian.net/browse/KDESKTOP-1045) in the narrow case reported by the user. 
A general fix will be proposed in a separate pull request.
[KDESKTOP-1045]: https://infomaniak.atlassian.net/browse/KDESKTOP-1045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KDESKTOP-1045] Removes unused calls and variables from ConflictResolverWorker::generateOperations

src/gui/synthesispopover.cpp
We receive a sentry when we do not find an update even if the app is not locked.
=> Fix false positive sentry (require for 3.6.3)

src/libsyncengine/syncpal/syncpal.cpp, src/libsyncengine/syncpal/syncpalworker.cpp
This issue addresses a bug implemented by the use of a copy of the snapshot. The copy operation is not calling the liveSnapshot 'startRead' method, causing it to keep its 'updated' member as true.
=> Fix infinit loop sync.

src/gui/debuggingdialog.cpp
The Log uploader don't send old logs when log folder is too small.
=> Fix log uploader on small logs.

src/gui/debuggingdialog.cpp, src/gui/parametersdialog.cpp, src/gui/synthesispopover.cpp, src/gui/synthesispopover.h, src/libsyncengine/jobs/network/abstractnetworkjob.cpp, src/libsyncengine/requests/serverrequests.cpp, translations/client_de.ts, translations/client_es.ts, translations/client_fr.ts, translations/client_it.ts
=> Kdesktop 1084 handle qa feedback 3.6.3

src/libsyncengine/propagation/executor/executorworker.cpp, src/server/appserver.cpp, src/server/appserver.h, src/server/socketapi.cpp, src/server/socketapi.h, src/server/socketlistener.cpp, src/server/socketlistener.h, test/libsyncengine/jobs/testjobmanager.cpp
Summary: Fix issue with random crashes during app download step related to QLocalSocket internal buffer management.
Description: We have identified an issue where the application crashes randomly during the download step, initially thought to be related to large sync operations.
Upon investigation, the error occurs within the vfsForceStatus call, specifically when the socket->write method is invoked within SocketListener::sendMessage. The root cause appears to be inconsistencies in the QLocalSocket's internal buffer, which occasionally becomes empty or changes size unpredictably.
During downloads, the write method is called in a dedicated thread, while some QLocalSocket private callback rely on connect and are  handled by the event loop (in the main thread). This asynchronous handling can …
=> Fix vfs socket bug.

src/libsyncengine/jobs/network/API_v2/csvfullfilelistwithcursorjob.cpp
We encountered an issue due to network failure, as we only received the header but an empty CSV file. This led to the directory being considered empty and resulted in the deletion of local items. This was compounded by a bug in the security check during advanced sync, which caused actual deletions. This issue has been addressed in another pull request (PR).
Going forward, the back-end will always send a CSV header and we will systematically check for its presence to differentiate between network failures and empty CSV files.
=> Check that the response is never empty for CsvFullFileListWithCursorJob.

src/libcommon/utility/utility.cpp, src/libcommon/utility/utility.h, src/libsyncengine/jobs/network/API_v2/csvfullfilelistwithcursorjob.cpp, src/libsyncengine/syncpal/syncpal.cpp, src/libsyncengine/syncpal/syncpal.h, src/libsyncengine/syncpal/syncpalworker.cpp, src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp, src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.h, test/libsyncengine/propagation/executor/testintegration.cpp, test/libsyncengine/propagation/executor/testintegration.h, test/libsyncengine/update_detection/file_system_observer/testcomputefsoperationworker.cpp, test/test_utility/testhelpers.h
File opened in [Logic Pro pour Mac](https://www.apple.com/fr/logic-pro/)  are renamed with conflicted suffix because of a size mismatch detected in step 2.
This happens when all the modification dates (local, remote and DB) are the same but the size differ between local and remote. This situation should never happen in theory, but actually does as it seems that `Logic Pro` is able to modify a file without updating its modification date.
Use an environment variable to activate the detection of partially dowloaded files.
=> Kdesktop 1033 file size mismatch detected for logic pro files

translations/client_fr.ts
In **most** cases, the estimated remaining time before synchronisation completion (expressed in years, days, hours, minutes or seconds) will be of the **female and plural form** when translated to french.
In the example below, we will read _"7 heures restantes"_ instead of _"7 heures restant"_ after this change.
This pull-request does not address the case of singular or masculine forms (e.g, day(s)), as they are deemed less frequent.
=> Tiny enhancement of a french translation for sync progress

src/libcommon/utility/jsonparserutility.h, src/libsyncengine/update_detection/file_system_observer/localfilesystemobserverworker.cpp, src/libsyncengine/update_detection/file_system_observer/remotefilesystemobserverworker.cpp, src/libsyncengine/update_detection/file_system_observer/remotefilesystemobserverworker.h, src/libsyncengine/update_detection/file_system_observer/snapshot/snapshot.h, src/libsyncengine/update_detection/file_system_observer/snapshot/snapshotitem.h, test/libsyncengine/jobs/network/testsnapshotitemhandler.cpp, test/libsyncengine/propagation/operation_sorter/testoperationsorterworker.cpp, test/libsyncengine/reconciliation/conflict_finder/testconflictfinderworker.cpp, test/libsyncengine/reconciliation/conflict_resolver/testconflictresolverworker.cpp, test/libsyncengine/update_detection/file_system_observer/testcomputefsoperationworker.cpp, test/libsyncengine/update_detection/file_system_observer/testsnapshot.cpp
All files created on remote while the app was running were detected as link. Therefore, the app would download the file content even in LiteSync mode.
=> KDESKTOP-1192-Files-downloaded-at-creation-in-LiteSync-mode

src/libsyncengine/syncpal/syncpal.cpp, src/server/socketapi.cpp
`2024-09-09 14:05:22:061 [I] (0x201740f00) socketapi.cpp:266 - Received SocketAPI message - msg=RETRIEVE_FOLDER_STATUS:/Users/clement/kDrive3/test_from_remote socket=0x1356043d0
2024-09-09 14:05:22:062 [I] (0x201740f00) socketlistener.cpp:50 - Sending SocketAPI message --> STATUS:OK:/Users/clement/kDrive3/test_from_remote to 0x1356043d0
...
2024-09-09 14:05:22:074 [I] (0x201740f00) socketapi.cpp:266 - Received SocketAPI message - msg=RETRIEVE_FILE_STATUS:/Users/clement/kDrive3/testé copy.txt socket=0x1356043d0
2024-09-09 14:05:22:075 [I] (0x201740f00) socketlistener.cpp:50 - Sending SocketAPI message --> STATUS:NOP:/Users/clement/kDrive3/testé copy.txt to 0x1356043d0`
Encoding issue. We were trying to retrieve a value in the remote snapshot using a local path
=> KDESKTOP-1197-Status-not-visible-in-Finder-for-NFD-encoded-files

extensions/MacOSX/kDriveFinderSync/Extension/xpcClient.m, extensions/MacOSX/kDriveFinderSync/Extension/xpcClientProxy.m, extensions/MacOSX/kDriveFinderSync/kDrive/AppDelegate.h, extensions/MacOSX/kDriveFinderSync/kDrive/AppDelegate.m, extensions/MacOSX/kDriveFinderSync/kDrive/Base.lproj/MainMenu.xib, src/libcommonserver/utility/utility.cpp, src/libcommonserver/utility/utility.h, src/libcommonserver/utility/utility_mac.cpp, src/libcommonserver/utility/utility_mac.mm, src/server/appserver.cpp
Finder extension was not started correctly anymore on macOS 15.0.
The fix consist of 2 points:
- in extension: fix the way we cast NSet
- in app: restart the Finder extension at app start up and when adding/removing syncs (following recommendation from https://www.codecentric.de/wissens-hub/blog/finder-sync-extension)
=> KDESKTOP-1174-Test-on-macOS-15.0

src/libcommonserver/log/customrollingfileappender.cpp, src/libcommonserver/log/customrollingfileappender.h, test/libcommonserver/log/testlog.cpp
When the log reaches its maximum size, a new log is successfully created. However, it has been observed that the old log is being deleted instead of being renamed with a ".0" suffix as expected. This behavior is causing us to lose historical log data and making it difficult to troubleshoot issues.
=> Kdesktop 1229 log rotation issue old logs being deleted instead of being renamed

src/libcommon/log/customlogwstream.h
We have encountered an issue where the LOGW is not rendering correctly in Sentry. This issue is causing difficulties in tracking and resolving errors in our application.
=> Fix CustomLogWStream &operator<<(const wchar_t *str) operator.

src/libcommon/utility/utility.cpp, test/libcommon/utility/testutility.cpp
The proposed changes replace a custom logic by a standard implementation of the lexicographical comparison of `std::vector<int>`.
=> Simplifies the implementation of CommonUtility::isVersionLower

src/libcommon/utility/types.cpp, src/libcommon/utility/types.h, src/libsyncengine/jobs/network/API_v2/upload_session/abstractuploadsessionjob.cpp, src/libsyncengine/jobs/network/API_v2/upload_session/driveuploadsession.cpp, src/libsyncengine/jobs/network/API_v2/upload_session/driveuploadsession.h, src/libsyncengine/jobs/network/API_v2/upload_session/loguploadsession.cpp, src/libsyncengine/jobs/network/API_v2/upload_session/uploadsessionstartjob.cpp, src/libsyncengine/jobs/network/API_v2/upload_session/uploadsessionstartjob.h, src/libsyncengine/propagation/executor/executorworker.cpp, src/libsyncengine/syncpal/syncpal.cpp, src/server/appserver.cpp, test/libsyncengine/jobs/network/testnetworkjobs.cpp
We should provide a fileId instead of a filename for editing. Previously, it was functioning only due to the 'conflict=Version' argument in query parameters.
=> Kdesktop 1286 fix in executor worker upload session constructor

src/libsyncengine/syncpal/syncpalworker.cpp, src/libsyncengine/update_detection/file_system_observer/folderwatcher_win.cpp, src/libsyncengine/update_detection/file_system_observer/snapshot/snapshot.cpp, src/libsyncengine/update_detection/file_system_observer/snapshot/snapshot.h, test/libsyncengine/update_detection/file_system_observer/testlocalfilesystemobserverworker.cpp, test/libsyncengine/update_detection/file_system_observer/testlocalfilesystemobserverworker.h
This PR addresses an issue which generates duplicate entries in the snapshot. When the filesystem quickly sends a `MOVE` followed by a `DELETE` for the same file.
=> Kdesktop 1285 fix in folderwatcher.cpp

infomaniak-build-tools/translate_release_notes.py
This is the companion pull-request of the following Gitlab merge request: https://gitlab.infomaniak.ch/christophe.larchier/infomaniakdrive-build-tools/-/merge_requests/6
The goal is to manage uniformly release notes with respect to OS and language.
=> Adds the OS and the language suffix for every OS and language

src/libsyncengine/jobs/network/API_v2/csvfullfilelistwithcursorjob.cpp, src/libsyncengine/jobs/network/API_v2/csvfullfilelistwithcursorjob.h, src/libsyncengine/update_detection/file_system_observer/remotefilesystemobserverworker.cpp, test/libsyncengine/jobs/network/testnetworkjobs.cpp, test/libsyncengine/jobs/network/testnetworkjobs.h, test/libsyncengine/jobs/network/testsnapshotitemhandler.cpp
The end of line delimiter (#EOF) is now expected at the end of the CSV file. If not received, the sync must be stopped and the snapshot rebuild to avoid unwanted delete operations.
=> KDESKTOP-1232-CSV-parsing-error-after-network-interruption

src/libcommon/utility/jsonparserutility.h
Before this PR, if the key was not found or was found but empty, the `JsonParserUtility::extractValue` method would return true and leave the `val` variable unchanged.
This behavior caused issues in the following scenario:
```cpp
if (!JsonParserUtility::extractValue(actionObj, fileTypeKey, tmpStr)) {
return ExitCode::BackError;
}
actionInfo.snapshotItem.setType(tmpStr == fileKey ? NodeType::File : NodeType::Directory);
if (!JsonParserUtility::extractValue(actionObj, symbolicLinkKey, tmpStr, false)) {
return ExitCode::BackError;
}
actionInfo.snapshotItem.setIsLink(!tmpStr.empty());
```
If `symbolicLinkKey` was not found, `tmpStr` would retain the value of `fileTypeKey`, mistakenly treating the item as a link by assuming the link URL was not empty.
This PR modifies `extractValue` to clear …
=> JsonParserUtility::extractValue ensure to not return garbage value

src/libcommon/utility/types.h, src/libparms/db/parameters.h, src/libsyncengine/jobs/network/getappversionjob.cpp, src/libsyncengine/jobs/network/getappversionjob.h, src/server/updater/updatechecker.cpp
The flag "has_prod_next" should be used to know if the current app has been selected for the progressive update
=> KDESKTOP-1323-Updater-Use-flag-has_prod_next

src/server/updater/sparkleupdater.mm
A "Checking for updates" window with a progress bar briefly appears while starting Sparkle updater. It is not required since the information is already known from the kStore.
=> KDESKTOP-1331-Updater-Hide-the-Checking-for-updates-window

src/libsyncengine/propagation/executor/executorworker.cpp, src/libsyncengine/propagation/executor/executorworker.h
Following https://github.com/Infomaniak/desktop-kDrive/pull/359, the method `hasRight` in Executor is not needed anymore. Remove it but keep the logic on special folders ("Common documents" and "Shared")
=> KDESKTOP-1330-Remove-hasRight-method-from-Executor

src/libsyncengine/progress/progressinfo.cpp
Currently, calling ProgressInfo::setProgress on an item that is not in the _currentItems list returns an error. It should instead behave as if !shouldCountProgress and return successfully.
This is problematic in the case of omitted operations, which will systematically generate an error. This error prevent us to correctly set the vfs and status of the file.
=> Bug fix: setProgress  should not exit with an error when the item progress is not managed.

src/libsyncengine/propagation/executor/executorworker.cpp, src/server/appserver.cpp
Vfs functions should return an ExitInfo struct:
https://infomaniak.atlassian.net/browse/KDESKTOP-1359?atlOrigin=eyJpIjoiNjIwYjRmMDUxNjIyNDE2Njk2ZTE4YjNiZDg5N2Q3YzgiLCJwIjoiaiJ9
=> Kdesktop 1356 mac os crash when a file is updated remotely and locked locally

src/libcommon/utility/utility.cpp, src/libcommon/utility/utility.h, src/libparms/db/parmsdbappstate.cpp
Because of a back limitation, the App ID was generated using a limited set of characters. This limitation has been removed on back side, we can remove it also on ours.
=> KDESKTOP-1366-App-ID-generated-on-a-limited-set-of-characters

src/server/updater/sparkleupdater.mm
Once the update has been accepted by the user, the package is downloaded by Sparkle and the user needs to start the update. If another update windows pops up before the validation, the next updates will fail.
Fix : Do not start a new update process if one is already ongoing
=> KDESKTOP-1360-Issues-with-Sparkle-updater

src/server/updater/abstractupdater.cpp, src/server/updater/sparkleupdater.h, src/server/updater/sparkleupdater.mm, src/server/updater/updatemanager.cpp
Sparkle keep the skipped version "forever". This PR aims to "forget" the skipped version if the user click on the "Update" button.
=> KDESKTOP-1399-Updater-Update-proposed-even-if-it-was-skipped

src/libsyncengine/propagation/executor/executorworker.cpp, src/libsyncengine/propagation/executor/executorworker.h, test/libcommonserver/CMakeLists.txt, test/libcommonserver/io/testopenfile.cpp, test/libsyncengine/propagation/executor/testexecutorworker.cpp, test/libsyncengine/propagation/executor/testexecutorworker.h, test/test_utility/timechecker.h
This PR addresses a critical issue in the `ExecutorWorker` class where concurrent access to the `TerminatedJobsQueue` caused a crash. It occurred during the execution of the `deleteFinishedAsyncJobs` method when multiple threads attempted to access `_terminatedJobs` without proper synchronization.
The root cause was identified as unsafe access to `_terminatedJobs`, a shared resource accessed concurrently by multiple threads. This led to race conditions and crashes, particularly when one thread was modifying the queue while another was reading or checking its contents (TerminatedJobsQueue::front()).
1. **Made `TerminatedJobsQueue` Thread-Safe:**
- Converted `TerminatedJobsQueue` into a thread-safe container by inheriting from `std::recursive_mutex`.
- Used `std::scoped_lock` for locking …
=> Resolve Concurrent Access Issue in TerminatedJobsQueue

src/server/updater/abstractupdater.cpp
Missing return statement leads to the error status never set
=> KDESKTOP-1377-Fix-missing-return-in-case-of-error

src/libcommonserver/utility/utility_mac.cpp, src/libcommonserver/utility/utility_mac.mm
The changes pertain only to the MacOSX platform.
The errors logged by `moveItemToTrash` are **not** readable in a text editor because of special quote characters. 
The proposed fixe makes these errors readable.
=> Use a wide string to log errors in moveItemToTrash (MacOSX)

src/libsyncengine/propagation/executor/executorworker.cpp, src/libsyncengine/update_detection/update_detector/node.h, src/libsyncengine/update_detection/update_detector/updatetree.cpp, src/libsyncengine/update_detection/update_detector/updatetree.h, src/libsyncengine/update_detection/update_detector/updatetreeworker.cpp, src/libsyncengine/update_detection/update_detector/updatetreeworker.h
Ensure that Node::_id's are consistent with the key of UpdateTree:_nodes.
=> [3.6.8] File content exchange issue (#442)

.github/workflows/macos.yml
Avoid the error "database is locked Possibly there are two concurrent builds running in the same filesystem location"
=> macOS CI - Avoid "database is locked" build error

src/libsyncengine/syncpal/isyncworker.cpp
There is a crash in the destructor of `ISyncWorker` if the worker has not been joined beforehand. This fix should prevent the crash and allow for a graceful exit.  
I am still investigating the issue that led to the destruction of a worker that has not been stopped yet.
=> Kdesktop 1510 crash in 3.6.8

src/libsyncengine/propagation/executor/executorworker.cpp
Minor formatting fixes in _Executor_ logs.
=> Fixes formatting error in executor (duplicate 'name' and duplicate quotes)

src/server/updater/updatechecker.h, src/server/updater/updatemanager.h
Use only "Production" distribution channel as long as we do not have an automatic update mechanism on Linux
=> KDESKTOP-1481-Do-not-allow-progressive-update-on-Linux

src/libsyncengine/update_detection/update_detector/updatetreeworker.cpp, test/libsyncengine/update_detection/update_detector/testupdatetreeworker.cpp, test/libsyncengine/update_detection/update_detector/testupdatetreeworker.h
For file (not directory), the path of deleted nodes in the update tree was not corrected if a parent was moved. Therefor, this leads to errors in the update tree and generated operations.
ex:
`2025-01-27 16:05:23:547 [D] (0x16dcbf000) operationgeneratorworker.cpp:268 - *1* Move operation 0 to be propagated on Remote(2) replica from "A" to "A" (ID: 48917403)`
=> KDESKTOP-1523-Move-issue-in-Update-Tree

src/libsyncengine/propagation/executor/executorworker.cpp, src/libsyncengine/propagation/executor/executorworker.h, test/libsyncengine/jobs/network/testnetworkjobs.cpp, test/libsyncengine/propagation/executor/testexecutorworker.cpp, test/libsyncengine/propagation/executor/testexecutorworker.h
Cause: Attempting to delete the operation corresponding node, that does not exist for a zombie placeholder.
=> Kdesktop 1525 the sync restarts after blacklisting a dehydrated placeholder

src/libsyncengine/syncpal/syncpal.h, test/libsyncengine/CMakeLists.txt, test/libsyncengine/propagation/operation_sorter/testoperationsorterworker.cpp, test/libsyncengine/propagation/operation_sorter/testoperationsorterworker.h, test/test_classes/testinitialsituationgenerator.cpp, test/test_classes/testinitialsituationgenerator.h, test/test_utility/testhelpers.h
Generating and filling data structures for tests (DB and update trees) is very off-putting and redundant.
This PR aims to create a simple helper class that will fill automatically those data. The user have to provide the desired structure as only input.
=> KDESKTOP-1544-Simplify-the-generation-of-data-structure-for-test

src/libsyncengine/jobs/network/API_v2/downloadjob.cpp, src/libsyncengine/jobs/network/API_v2/downloadjob.h, test/libsyncengine/jobs/network/testnetworkjobs.cpp
Hydrated placeholder that was edited from remote replica were renamed with "conflict" suffix locally
=> KDESKTOP-1552 - Fix download job

src/server/appserver.cpp
After installation, and depending on the time at which `LiteSync` authorizations are given by a MacOS user, the _Vfs_ start failure errors 
remains persistently in _desktop-kDrive GUI_ even if the _Vfs_ is subsequently and successfully initialized.
The issue has been frequently reproduced.
=> [HOTFIX] Initialize SyncPal even if Vfs has not started yet

admin/osx/macosx.pkgproj.cmake
Give the write permission to the "admin" group to allow to delete the app on macOS 15.3
=> Fix app permissions

src/libcommonserver/utility/utility.cpp, test/libsyncengine/jobs/network/testnetworkjobs.cpp
This PR optimizes the `Utility::normalizedSyncName` method on Windows, significantly improving its performance.  
**Benchmark Results:**  
- **Before optimization:** ~1.5s for 1,000,000 characters  
- **After optimization:** ~0.65s for 1,000,000 characters  
- **Performance gain:** More than **2x faster**  
This method is called frequently, particularly through `normalizeSyncPath` and `checkIfSameNormalization`, both of which are often used within loops. Reducing execution time here helps improve overall synchronization performance (🚀)
=> Performance improvement of `Utility::normalizedSyncName` on Windows.

src/libsyncengine/jobs/network/API_v2/downloadjob.cpp, test/libsyncengine/jobs/network/testnetworkjobs.cpp
Due to recent changes in download job beahviour, a 0-byte file download now leads to a `BackError InvalidSize`, which  leads in turn to the sync failure.
Added a new test case in `TestNetworkJobs::testDownload` to verify that downloading an empty file is handled correctly.
=> KDesktop 1586: 0-byte files to develop

src/server/appserver.cpp, src/server/appserver.h, src/server/updater/abstractupdater.cpp, src/server/updater/abstractupdater.h, src/server/updater/linuxupdater.cpp, src/server/updater/linuxupdater.h, src/server/updater/sparkleupdater.h, src/server/updater/sparkleupdater.mm, src/server/updater/updatemanager.cpp, src/server/updater/updatemanager.h, src/server/updater/windowsupdater.cpp, src/server/updater/windowsupdater.h, test/server/updater/testabstractupdater.cpp
The initial impetus of these changes comes from a `cppcheck` warning about the `static` method `AbstractUpdater::unskipVersion` that was redefined as another `static` method of the derived class `SparkelUpdater`.
The `static` qualifier of the method `unskipVersion` is now removed so that polymorphism can be used appropriately. Each derived class of `AbstractUpdater` is additionally turned into a singleton.
=> [KDESKTOP-1129] Designs updaters as singletons

src/libsyncengine/syncpal/syncpalworker.cpp, test/test_utility/timeouthelper.cpp
TestSyncPalWorker::testInternalPause1() fails sometime. This PR aims to fix that
=> Fix TestSyncPalWorker::testInternalPause1()

src/libsyncengine/update_detection/file_system_observer/remotefilesystemobserverworker.cpp
This is a regression introduced in https://github.com/Infomaniak/desktop-kDrive/pull/599 and  https://github.com/Infomaniak/desktop-kDrive/pull/544.
The `_initializing` must be set to `false` as soon as the remote snapshot is created and before sending the first LongPoll request
=> Regression - Step 1 slow down

src/libsyncengine/reconciliation/platform_inconsistency_checker/platforminconsistencycheckerworker.cpp, src/libsyncengine/syncpal/syncpal.h, src/libsyncengine/syncpal/tmpblacklistmanager.cpp, src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp, src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.h, test/libsyncengine/reconciliation/platform_inconsistency_checker/testplatforminconsistencycheckerworker.cpp, test/libsyncengine/update_detection/file_system_observer/testcomputefsoperationworker.cpp, test/libsyncengine/update_detection/file_system_observer/testcomputefsoperationworker.h, test/test_classes/testinitialsituationgenerator.cpp, test/test_classes/testinitialsituationgenerator.h
This [PR](https://github.com/Infomaniak/desktop-kDrive/pull/585/commits) introduced a regression that led to the propagation of an unwanted _Delete_ operation in the case where an item is renamed on the remote replica without an unsupported character.
This PR correct the problem with 2 patches:
- The local items are not renamed anymore in the `PlatformInconsistencyCheckerWorker` but only temporary blacklisted.
- All blacklists are now checked in `ComputeFSOperationWorker` for each item.
=> KDESKTOP-1429-Windows-A-forbidden-character-can-cause-an-infinite-sync-loop

src/libsyncengine/update_detection/file_system_observer/localfilesystemobserverworker.cpp
Syncs are started during file hydration because macOS trigger `OperationType::Rights` events. Those events will therefore be ignored if the file has not changed (same size and same modification time).
=> KDESKTOP-853 - Do not update snapshot item if file has not changed

extensions/windows/cfapi/Vfs/cloudprovider.cpp
On Windows, during file hydration, a lot of log is generated by the extension:
```
...
2025-01-08 10:11:24:510 [D] (11004) vfs_win.cpp:110 - "utilities.cpp" - 101 - File path = C:\Users\Clément\kDrive\test_big_folder\infomaniak\test_big_file: creationTime = 9:51:40, accessTime = 20:51:44, writeTime = 20:51:44
2025-01-08 10:11:24:514 [D] (11004) vfs_win.cpp:110 - "utilities.cpp" - 101 - File path = C:\Users\Clément\kDrive\test_big_folder\infomaniak\test_big_file: creationTime = 9:51:40, accessTime = 20:51:44, writeTime = 20:51:44
2025-01-08 10:11:24:514 [D] (11004) vfs_win.cpp:110 - "cloudprovider.cpp" - 316 - Execute transfer: offset = 3735552000, size = 4096000
2025-01-08 10:11:24:519 [D] (11004) vfs_win.cpp:110 - "utilities.cpp" - 101 - File path = …
```
=> KDESKTOP-1472-File-hydration-generate-a-lot-of-log-on-Windows

src/gui/parametersdialog.cpp, src/libcommon/utility/types.cpp, src/libcommon/utility/types.h, src/libcommonserver/utility/utility.cpp, src/libcommonserver/utility/utility.h, src/libsyncengine/reconciliation/platform_inconsistency_checker/platforminconsistencycheckerutility.cpp, src/libsyncengine/reconciliation/platform_inconsistency_checker/platforminconsistencycheckerutility.h, src/libsyncengine/reconciliation/platform_inconsistency_checker/platforminconsistencycheckerworker.cpp, src/libsyncengine/syncpal/syncpal.cpp, src/libsyncengine/syncpal/syncpal.h, src/libsyncengine/syncpal/tmpblacklistmanager.cpp, src/libsyncengine/syncpal/tmpblacklistmanager.h, test/libsyncengine/jobs/network/testnetworkjobs.cpp, test/libsyncengine/reconciliation/platform_inconsistency_checker/testplatforminconsistencycheckerworker.cpp, test/libsyncengine/reconciliation/platform_inconsistency_checker/testplatforminconsistencycheckerworker.h, test/libsyncengine/syncpal/testsyncpal.cpp, test/test_classes/syncpaltest.h, test/test_utility/localtemporarydirectory.cpp
If a local item's name contains only spaces, it will be refused by the back end. However, the error message is not explicit in the app.
**Steps to reproduce:**
On macOS:
- Pause the sync
- Create a new directory on local replica named “ “ (single space character)
- Start the sync
=> Kdesktop 1563 introducing an invalid character in a folder name causes an infinite synchronisation loop

src/libsyncengine/update_detection/file_system_observer/localfilesystemobserverworker.cpp
It is not causing issues in the app behavior, but it leads to an assertion in debug when we create a file on Windows.
=> Quick Fix - Only get the pinState of placeholders

cmake/modules/NSIS.template.nsi.in, extensions/windows/cfapi/Vfs/Vfs.vcxproj, extensions/windows/cfapi/Vfs/cloudproviderregistrar.cpp
Several clients reported that, on Windows, links (`.lnk`) to a file or folder inside a **kDrive sync directory** were systematically broken after each app update.
⚠️ **Note:** The following explanation is based on observations, assumptions, and limited documentation. It is sufficient to address our issue but should not be considered as an absolute truth.
After investigation, it appears that `.lnk` files do **not** point directly to a path but rather to an **item ID** (which is different from the `nodeId`). This mechanism allows links to remain valid even if the file or folder is moved.
However, in a **LiteSync** folder, items exist in a **dedicated namespace**, with their own set of unique IDs (which can be seen as a combination of `fileID` and `namespaceID` where the `namespace` is the …
=> Kdesktop 1478 bug .lnk lors des maj windows

src/libcommon/utility/types.h, src/server/updater/updatechecker.cpp, test/server/updater/testupdatechecker.cpp
The app crashes when opening Preferences and Release Notes or clicking "Update" after ignoring an update and losing network access (for long enough to let a getVersion request fail)
1. A new update is available.  
2. Start the app and wait for the update notification.  
3. Ignore the update.  
4. Turn off network access.  
5. Wait 1 hour, allowing a `getVersionInfo` job to fail.  
6. Open Preferences and Release Notes or click "Update" → the app crashes.  
In `UpdateChecker::versionInfo`:
- When `_versionsInfo` is empty, `betaVersion`, `internalVersion`, and `prodVersion` were automatically set to the default version.  
- However, the default version tag is an empty string (`""`).  
- When inserting it into `sortedVersionList`, the `VersionInfoCmp` method attempts to call `stoi` on `""`, …
=> Kdesktop 1635 crash in updater

infomaniak/kDrive.cmake, src/gui/adddriveloginwidget.cpp, src/libcommon/CMakeLists.txt, src/libcommon/utility/types.h, src/libcommon/utility/urlhelper.cpp, src/libcommon/utility/urlhelper.h, src/libcommonserver/utility/utility.cpp, src/libcommonserver/utility/utility.h, src/libsyncengine/jobs/network/API_v2/abstracttokennetworkjob.cpp, src/libsyncengine/jobs/network/getappversionjob.h, src/libsyncengine/jobs/network/login/abstractloginjob.cpp, test/libcommon/CMakeLists.txt, test/libcommon/test.cpp, test/libcommon/utility/testurlhelper.cpp, test/libcommon/utility/testurlhelper.h
Environment variable allowing to select prod or preprod URLs should be evaluated at runtime
=> KDESKTOP-1621-Preprod-env-variable-should-be-read-at-runtime

src/libcommon/utility/types.cpp, src/libcommon/utility/types.h, src/libcommon/utility/utility.cpp, src/libcommonserver/vfs/vfs.cpp, src/libsyncengine/jobs/network/getappversionjob.cpp
We should never offer to the user to use LiteSync on a Windows Server
=> KDESKTOP-1371-It-should-not-be-possible-to-activate-LiteSync-on-WindowsServer

src/libcommon/utility/utility.cpp, test/libcommon/utility/testutility.cpp, test/libcommon/utility/testutility.h
This PR improves the time performance of the `CommonUtility::RelativePath` function.  
The function takes a **root path** and a **target path** as input. It returns the portion of the target path that lies under the root path.  
- **Before Optimization:**  
- **Execution Time:** 8.3s for 200,000 calls  
- **Complexity:** O(n) in relation to the path length  
- **After Optimization:**  
- **Execution Time:** 1.6s for the same conditions  
- **Complexity:** Unchanged  
- Unit tests have been added and successfully executed on both the old and new implementations.  
- The only functional difference is that the old implementation did **not** support root paths ending with `/` or `\`, whereas the new one does.
=> Performance Improvement: `CommonUtility::RelativePath`  

.github/workflows/build-and-run-extended-tests.yml
As mentioned in the following issue, files generated by the runner which are not part of the git repository cannot be displayed as a preview: https://github.com/pavi2410/html-preview-action/issues/12
The scope of this PR has changed as it now removes the HTML preview action.
=> Remove the HTML preview Github action: generated files are not supported

src/libsyncengine/progress/progressinfo.cpp
This PR optimizes the initial sync performance, particularly when syncing a directory for the first time in **lite sync mode**.
In the current implementation, a significant amount of time is spent calculating the total download/upload progress during the initial sync.  
However, in **lite sync mode**, this is unnecessary as the total progress will **always be 0 bytes** (nothing is downloaded or uploaded).
To reduce the overhead, we now compute the total progress of ongoing uploads/downloads only:
- Every **1000 completed items**, or
- When there are **fewer than 100 items left in the queue**
This simple heuristic drastically reduces the time spent on computing progress in lite sync without sacrificing accuracy in normal sync scenarios.
Before (Initial synchronization of 264,063 items …
=> Optimize executor speed

src/libcommonserver/io/iohelper.cpp
`DirectoryIterator::next` was previously inefficient due to the creation of two iterators per call, just to obtain the `end` value. This is unnecessary, as we can retrieve the `end` value from the already constructed iterator.
Additionally, we frequently convert `std::error_code` to `ioError`, even when it’s not needed. Removing these redundant conversions simplifies the code and avoids unnecessary overhead.
These optimizations provide **significant performance improvements**:
**Case 1: Recursive traversal of a folder containing 100 subfolders, each with 1,000 files and 1,000 empty directories (200,100 items)**  
- Before: **38.078s**  
- After: **6.959s**
**Case 2: Recursive traversal of a folder containing 100 subfolders, each with 2,000 files (200,100 items)**  
- Before: **20s**  
- …
=> Kdesktop 1531 optimize io helper directory iterator

src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp, src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.h
This PR aims to fix a bug where the `computeFSOperationWorker` might abort on every sync, leading to the syncs restarting and looping indefinitely.
The problem is that the provided ID is always considered to be a local ID while it might be a remote one.
Regression inserted in commit : addacd110eee05ad58ddf2f5523094ae7cd6be5f
```
2025-04-15 16:00:57:660 [I] (0x16af6f000) syncpalworker.cpp:221 - *1* ***** Step <Compute FS operations> start
2025-04-15 16:00:57:660 [D] (0x16af6f000) isyncworker.cpp:45 - *1* Worker Compute FS Operations start
2025-04-15 16:00:57:660 [D] (0x16b573000) computefsoperationworker.cpp:42 - *1* Worker started: name=Compute FS Operations
2025-04-15 16:00:57:662 [D] (0x16b22b000) jobmanager.cpp:229 - Starting job 542 with priority 1
2025-04-15 16:00:57:662 [D] …
```
=> Fix bug in compute FS operation

src/libsyncengine/jobs/jobmanager.cpp, src/libsyncengine/jobs/jobmanager.h, test/libsyncengine/propagation/executor/testintegration.cpp
**Avoid double call to `JobManager::clear()` without `reset()`**
Fixes a crash on macOS caused by calling `JobManager::clear()` twice without an intermediate call to `JobManager::reset()`. According to the Poco documentation, `Poco::ThreadPool::defaultPool().stopAll()` should only be called once and just before the thread pool is deleted. While this doesn't currently cause issues on Windows, it's explicitly discouraged and leads to the observed crash on macOS.
=> Do not call JobManager::clear() twice

src/gui/synthesispopover.cpp
The links to the synchronization folders needed to be refreshed after each drive selection in synthesis pop-over widget.
=> [KDESKTOP-1017] Refresh the sync folder links after drive selection

src/libsyncengine/propagation/operation_sorter/operationsorterfilter.cpp, src/libsyncengine/propagation/operation_sorter/operationsorterworker.cpp, src/libsyncengine/update_detection/update_detector/node.cpp, src/libsyncengine/update_detection/update_detector/node.h, src/libsyncengine/update_detection/update_detector/updatetreeworker.cpp, test/libsyncengine/propagation/operation_sorter/testoperationsorterworker.cpp, test/libsyncengine/propagation/operation_sorter/testoperationsorterworker.h
There is a crash in `OperationSorterWorker` due to missing condition in the newly added "filter" class.
=> Crash in OperationSorterWorker

src/server/appserver.cpp
I could not reproduce the crash on Windows. However, based on the received sentry events, I tried to exit the function with an appropriate error before the crash.
=> Return a LogicError if syncPal is not found

src/server/updater/updatechecker.cpp
Calling the api with a user id 0 lead to a 422 respons wich block the update process.
=> Never call the kStore api with a user id 0.

infomaniak-build-tools/linux/build-release-appimage-amd64.sh, infomaniak-build-tools/linux/build-release-appimage-arm64.sh
Script `build-release-arm64-via-podman.sh` is not terminating correctly because of this empty suffix variable
=> Remove suffix from appImage name

src/libcommon/CMakeLists.txt, src/libcommon/utility/types.h, src/libcommon/utility/utility.cpp, src/libcommon/utility/utility.h, src/libcommon/utility/utility_win.cpp, src/libcommonserver/CMakeLists.txt, src/libcommonserver/utility/utility.cpp, src/libcommonserver/utility/utility.h, src/libsyncengine/db/syncdb.cpp, src/server/requests/serverrequests.cpp, test/libcommonserver/utility/testutility.cpp, test/libsyncengine/update_detection/file_system_observer/testsnapshot.cpp, test/test_utility/testhelpers.cpp
This PR aims at sharing the utility function that computes the NFC and NFD normalizations of a file name with the `gui` module. In a forthcoming PR, the function `normalizedSyncName` will be used to ensure that file exclusion via template takes both normalizations into account.
=> [KDESKTOP-1199] Defines a log-free normalizedSyncName function in libcommon/utility (to be used in gui)

src/libcommon/utility/types.h, test/libcommon/utility/testtypes.cpp
The aim of this PR is to avoid having to edit the tests each time an Exicode or cause is added or removed.
=> Replace hardcoded ExitInfo int value.

test/libcommon/CMakeLists.txt, test/libcommonserver/CMakeLists.txt, test/libparms/CMakeLists.txt, test/libsyncengine/CMakeLists.txt, test/server/CMakeLists.txt
This pull request updates the `CMakeLists.txt` files for multiple test libraries to use the dynamically linked versions of the CppUnit library on Windows. This change ensures consistency in linking and may address compatibility or runtime issues related to static vs. dynamic linking.
* `test/*/CMakeLists.txt`: Updated to use `cppunitd_dll.lib` and `cppunit_dll.lib` for debug and optimized builds, respectively, instead of their static counterparts.
=> fix(cmake): update cppunit library links to use dynamic versions

src/libsyncengine/reconciliation/conflict_resolver/conflictresolverworker.cpp, test/libsyncengine/reconciliation/conflict_resolver/testconflictresolverworker.cpp
This PR fixes in particular the following issue:
- Create and fully synchronize two folders `A` and `B`.
- Pause the synchronization.
- Locally, move `A` into `B`.
- Remotely, move `B` into `A`.
**Actual outcome:** 
- Assertion failure in _Debug_ mode (`node.cpp:276 - Condition failure: "isValid()" in file node.cpp`).
- The two folders are deleted in _Release_ Mode.
Once applied, this fix ensures that there is no assertion failure and the final situation is 
```
└── A
└── B
```
=> Kdesktop 1714 Set move origin info in undo move

src/libsyncengine/propagation/operation_sorter/operationsorterfilter.cpp, src/libsyncengine/propagation/operation_sorter/operationsorterfilter.h
Operation sorter filter data structures were not cleared on every new sync, which mean that nodes previously inserted remains in the filter even if they are not susceptible to be rearranged anymore.
=> Clear operation sorter filter data on every new sync

infomaniak-build-tools/windows/Readme.md
This pull request updates the `infomaniak-build-tools/windows/Readme.md` file to modify paths and instructions for building with Zlib. The changes standardize the use of `C:\Program Files (x86)` for storing Zlib files and adjust related CMake variables accordingly.
* Updated the extraction and build instructions to use `F:\Projects` for intermediate steps and then copy the `lib` and `include` folders to `C:\Program Files (x86)\zlib-1.2.11` for consistency.
* Adjusted the `ZLIB_INCLUDE_DIR` and `ZLIB_LIBRARY_RELEASE` CMake variables to point to the new location in `C:\Program Files (x86)\zlib-1.2.11`.
=> docs(readme): update Zlib installation paths to standardize directory usage

.clang-format
Add more Clang format rules to avoid this behavior:
It looks like that the git hook that reformat on commit was doing it differently than CLion.
=> Add more Clang-format rules

src/libcommonserver/log/log.cpp
The current behavior may cause a crash if the destructor of a static variable that relies on the logger is invoked after the (static) logger instance has already been destroyed.
For instance, the `CacheDirectoryHandler` destructor calls `IoHelper::deleteItem`, which attempts to use the logger if it's available. Since `Log::_instance` was not reset during destruction, the logger appears to be available, resulting in a crash.
=> Reset Log::_instance before calling log4cplus::Logger::shutdown()

infomaniak-build-tools/macos/build-release.sh
In the branch `KDESKTOP-1759-reformat-all-bash-scripts-according-to-coding-standards`, I changed some variables with internal script scope to lowercase.
In the `./infomaniak-build-tools/macos/build_release` script, this concerns variables such as `SRCDIR` to `src_dir` or `APPNAME` to `app_name`.
The variable `SPARKLEDIR` was renamed to `sparkle_dir`, but unfortunately, the variable `BUILD_DIR` was also renamed to `sparkle_dir` by mistake, which causes the application build to fail when using this script.
This PR also includes some various minor fixes in the same script.
See [this diff](https://github.com/Infomaniak/desktop-kDrive/pull/845/files#diff-a8538e7f1398591787570a875a5df595041f484768c45d01094034acef5de841) of the PR #845.
=> fix(macos/build-release.sh): correct variable names in `macos/build-release.sh` script

src/libsyncengine/reconciliation/conflict_resolver/conflictresolverworker.cpp, src/libsyncengine/reconciliation/conflict_resolver/conflictresolverworker.h, test/libsyncengine/reconciliation/conflict_resolver/testconflictresolverworker.cpp
| Remote Operations     | Local Operations      | Expected Result                             | Result |   Old behaviour  |
|-----------------------|-----------------------|---------------------------------------------|----------|---------------------------------------------|
| `delete Test`            | `edit a.txt`              | `a.txt` is moved to the resuce folder      | ✅     |  `a.txt` is moved to the resuce folder     |
| `delete a.txt`            | `edit a.txt`              | `a.txt` is recreated on remote side      | ✅     |  `a.txt` is recreated on remote side    |
| `edit a.txt`            | `delete Test`              | `a.txt` is moved to trash on remote side      | ✅    |  ❌  Sync loop |
| `edit a.txt`            | `delete a.txt`              |`a.txt` is recreated on local …
=> Fix missing conflict case: remote edit of dir/file.txt and local removal of dir.

.githooks/commit-msg
A git hook to check that your commit message respect conventional commit standards.
=> Conventional commits git hook

VERSION.cmake, src/gui/updater/updatedialog.cpp, src/gui/updater/updatedialog.h, src/gui/wizard/webview.cpp, src/libcommongui/matomoclient.cpp, src/libcommongui/matomoclient.h
This pull request updates the `UpdateDialog` UI in `src/gui/updater/updatedialog.cpp` by replacing the `QLabel` and `WebView` components with a `QTextBrowser` for displaying release notes.
* Replaced the `WebView` with a `QTextBrowser` to fix a rendering bug.
* Removed the static `QLabel`, as the "Release Notes" heading is included directly in the rendered HTML.
* Introduced `QNetworkAccessManager` to dynamically fetch release notes content.
* Removal of the old Matomo PageVisit (webview)
* And then creation of the new Matomo PageVisit tag
---
<div align="center">
This fixes a bug where the release notes were incorrectly rendered in the legacy WebView.
</div>
<table align="center">
<thead>
<tr>
<th>Bug</th>
<th>Fixed</th>
</tr>
</thead>
<tbody>
<tr>
<td align="center">
</td>
<td …
=> KDESKTOP 1764 - Windows Release Notes display fix

src/libsyncengine/requests/exclusiontemplatecache.cpp, src/libsyncengine/requests/exclusiontemplatecache.h, test/libsyncengine/requests/testexclusiontemplatecache.cpp, test/libsyncengine/requests/testexclusiontemplatecache.h
In a recent change, the normalization of the temporary exclusion `Icon\r` was modified in the exclusion template list.
As a result, these files are no longer excluded, which causes the folder icon to be lost on _macOS_. The file `Icon\r` is uploaded, but the backend automatically renames it to `Icon`, which triggers a local move. The file is then no longer recognized by _Finder_ as a folder icon file, since it no longer ends with `\r`.
To avoid such issues in the future, the `ExclusionTemplateCache` now automatically checks both NFD and NFC encodings when they differ.
=> Fix missing normalization in exclusion

extensions/windows/standard/KDOverlays/DllMain.cpp, extensions/windows/standard/KDOverlays/KDOverlayRegistrationHandler.cpp, extensions/windows/standard/KDOverlays/KDOverlayRegistrationHandler.h, extensions/windows/standard/KDOverlays/OverlayConstants.h
Windows only supports 15 shell overlay icon identifiers, shared between all applications. If there are more, Windows simply ignores the ones at the end of the alphabetical list. Major apps like OneDrive (7 overlays) and Dropbox (10 overlays) already use leading spaces in their registry keys to ensure higher priority (OneDrive uses 4, Dropbox and kDrive previously used 3).
As a result, when both Dropbox and OneDrive are installed (which is very common), kDrive’s icons are often excluded.
This PR introduces a dynamic solution:
- During installation or overlay registration, kDrive checks the registry for existing overlay icon keys.
- It automatically determines the maximum number of leading spaces used by other apps.
- kDrive then registers its overlays with **one more leading space** than …
=> Ensure kDrive Shell Overlay Icon Priority on Windows

src/gui/synchronizeditemwidget.cpp, src/libsyncengine/progress/progressinfo.cpp, src/libsyncengine/progress/progressinfo.h, src/libsyncengine/propagation/executor/executorworker.cpp, src/libsyncengine/propagation/executor/executorworker.h, src/libsyncengine/syncpal/syncpal.cpp, src/libsyncengine/syncpal/syncpal.h
This PR addresses two issues:
1. **Missing `nodeId` in local create operations synthesis**
When performing a local create, the `SynchronizedItem` sent to the GUI was missing the `nodeId` of the new remote item. This prevented certain features from being available in the operation summary, such as:
* **Sharing**
* **Open in the web**
**After the PR, these features are available:**
This is now fixed: the `nodeId` is properly propagated to the GUI.
2. **Crash when using `MenuItemWidget::setHidden()` on Windows/macOS**
On both Windows and macOS, calling `MenuItemWidget::setHidden()` caused `MenuWidget::exec()` to fail. This PR avoids unnecessary calls to `setHidden` that could lead to inconsistent or invalid menu states on those platforms.
=> Kdesktop 1833 Fix synthesis popover actions menu

src/libparms/db/parmsdb.cpp, src/libparms/db/parmsdb.h, test/libparms/db/testparmsdb.cpp, test/libparms/db/testparmsdb.h
This PR makes sure to insert missing columns in the `Parameters` database (as part of the `upgrade` method) before any request involving the modified columns. 
Unit tests are added to prevent regressions.
=> fix(parms-db-migration): upgrade columns before any other DB request

src/libcommon/utility/types.h, src/libsyncengine/propagation/executor/filerescuer.cpp, src/libsyncengine/propagation/executor/filerescuer.h, test/libsyncengine/propagation/executor/testfilerescuer.cpp, test/libsyncengine/propagation/executor/testfilerescuer.h
Following the implementation of the **kDrive rescue folder**, an issue was identified on **Windows** platforms:
- The method `FileRescuer::getDestinationPath` performs an unnecessary round-trip conversion:
- It converts a `w_str` (wide string) to a `str`, and then back to a `w_str`.
- During this conversion, **non-ASCII characters** (e.g., `é`, `è`, `ê`, `â`, etc.) are **corrupted or lost**.
- The resulting destination path contains **unknown or invalid characters** in place of the original non-ASCII ones.
- This causes the app to **crash later during a path normalization**.
---
This bug affects users in the following scenario:
1. A **conflict** occurs and triggers a file to be moved to the **rescue folder**.
2. The **original file path** contains **non-ASCII characters**.
3. A **file …
=> Kdesktop 1837 loss of non ascii characters in rescue folder path on windows and crash

test/test_utility/iohelpertestutilities.cpp
Add the reset of the function _rename defined inside the IoHelperTestUtilities class used to mock some `std::filesystem` functions.
Added the following line inside the `void IoHelperTestUtilities::resetFunctions()`:
```cpp
setRename(static_cast<void (*)(const SyncPath &srcPath, const SyncPath &destPath, std::error_code &ec)>(&std::filesystem::rename));
```
to [iohelpertestutilities.cpp](https://github.com/Infomaniak/desktop-kDrive/blob/c1ae775856fa3a06564303991b9cb3bd781793bc/test/test_utility/iohelpertestutilities.cpp).
=> fix(IoHelperTestUtilities): update resetFunctions to set `std::filesystem:rename`

conanfile.py
Fix CMake toolchain configuration issue in Qt Creator
This PR addresses a problem with the CMake toolchain configuration when building the project using the Qt Creator IDE on Windows. Specifically, it replaces the conditional generator expression for `CMAKE_MSVC_RUNTIME_LIBRARY` with a literal value based on the current build type. This resolves a failure in `conan_provider.cmake`, which expects a concrete value instead of a CMake generator expression.
This change ensures compatibility between Conan's generated toolchain and Qt Creator's Conan integration.
=> fix(conanfile): dynamically set CMAKE_MSVC_RUNTIME_LIBRARY based on build type

.github/workflows/build-and-run-extended-tests.yml, src/gui/adddriveserverfolderswidget.cpp, src/libcommon/utility/types.cpp, src/libcommon/utility/types.h, src/libcommonserver/utility/utility.cpp, src/libcommonserver/utility/utility.h, src/libsyncengine/jobs/network/API_v2/listing/longpolljob.cpp, src/libsyncengine/jobs/network/API_v2/listing/longpolljob.h, src/libsyncengine/jobs/network/abstractnetworkjob.cpp, src/libsyncengine/syncpal/syncpalworker.cpp, src/libsyncengine/update_detection/file_system_observer/remotefilesystemobserverworker.cpp
This PR is following the event https://infomaniakstatus.com/fr/JnqlybPlEr/ where an issue with the LongPoll on backend side leads to all the desktop apps to send thousands of `listing/continue` requests/s.
The correction consists in no longer ignoring 502 errors from LongPoll requests. They were previously considered as success and a `listing/continue` request was sent afterward.
In addition, all 5XX HTTP errors are now handled in the same way: the worker exit with exit code `BackError` and exit cause `Http5xx`, leading to the sync being paused for 1 minute.
Depends on #957
=> Do not ignore HTTP 500 errors in LongPoll

src/libcommon/utility/jsonparserutility.h, src/libsyncengine/jobs/network/API_v2/upload/uploadjobreplyhandler.cpp
If no creation time was previously set on remote side, after editing a file locally, its local value was lost and `0` was inserted in DB instead.
We now keep local creation time if the remote value is `null` or `0`.
=> Keep local creation time if remote value is null

src/libcommongui/matomoclient.cpp
Fix this warning.
```
/Users/username/Projects/desktop-kdrive/src/libcommongui/matomoclient.cpp:74:68: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
74 |         connect(piwikNAM, &QNetworkAccessManager::finished, this, [this](const QNetworkReply* reply) {
|                                                                    ^~~~
1 warning generated.
```
=> chore(matomo-client): remove unnecessary 'this' pointer in lambda connection

src/libsyncengine/update_detection/file_system_observer/folderwatcher_linux.cpp, test/libsyncengine/update_detection/file_system_observer/testfolderwatcherlinux.cpp
These changes relate to synchronization issues reported by Linux users (some of which are synchronizing virtual python environments or download folders).
The goal is to let the `inotifywatch` registration process continue as far as no known blocking issue is detected (e.g., insufficient memory or insufficient number of watches are blocking issues, for which a user action is required).
Details have been added to log messages. These messages should help debug and troubleshoot the unhandled (as of yet) registration issues. Note that such unhandled issues do not seem to have impacted negatively user synchronizations in the past in any **obvious way**.
=> [KDESKTOP-TRELLO-1027] Do not raise an error when a folder is removed before being registered

.github/actions/build_linux_amd/action.yml, .github/actions/build_macos/action.yml, .github/actions/build_windows/action.yml, .github/actions/test_linux/action.yml, .github/actions/test_macos/action.yml, .github/actions/test_windows/action.yml
Added steps in `action.yml` to fetch and upload uncached dependencies for Linux, macOS, and Windows builds. These dependencies are the vfs lib and `.lst` files which can change often across PRs.
=> ci: Add uncached dependency handling for builds

src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp, test/libsyncengine/update_detection/file_system_observer/testcomputefsoperationworker.cpp, test/libsyncengine/update_detection/file_system_observer/testcomputefsoperationworker.h
This PR adds unit tests  for the `ComputeFSOperationsWorker::updateSyncNode` method.
**Note.** This PR has changed its scope after realizing that the correct resolution of the blacklisted `sync_node` update problem should be done as in https://github.com/Infomaniak/desktop-kDrive/pull/998. After this change of scope, only the unit tests remain relevant.
=> chore(sync-node-table): add unit tests for the `updateSyncNode` method

.github/workflows/update_kstore.yml
This PR fixes the invalid workflow configuration in `.github/workflows/update_kstore.yml` that was causing GitHub to flag the file as invalid on every commit.  
The issue was that the workflow defined an input with `type: environment` under the `workflow_call` trigger.  
While `type: environment` is supported for `workflow_dispatch` (manual runs), it is **not** supported for `workflow_call` (when the workflow is invoked by another workflow). For `workflow_call`, only `string`, `boolean`, and `number` are valid input types.  
Because the file was invalid, GitHub’s workflow linter failed on every commit, even if the workflow wasn’t actually triggered. This made it look like the workflow was “failing” on each push.  
**Changes in this PR:**  
- Changed `type: environment` → `type: string` …
=> Fix `update_kstore.yml` invalid workflow definition for `workflow_call`  

src/libcommonserver/utility/utility.cpp, src/libsyncengine/syncpal/syncpal.h, src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp, src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.h, src/libsyncengine/update_detection/file_system_observer/snapshot/snapshot.cpp, src/libsyncengine/update_detection/file_system_observer/snapshot/snapshot.h, test/libsyncengine/integration/testintegration.cpp, test/libsyncengine/update_detection/file_system_observer/testcomputefsoperationworker.cpp, test/libsyncengine/update_detection/file_system_observer/testcomputefsoperationworker.h
The following events were not handled properly by the `desktop-kDrive` application:
- A local item is deleted.
- A non-empty local folder is created and reuses the identifier of the deleted item.
Such a situation leads to a corruption of the local update tree: the local update tree which contains a temporary node for the folder created locally but this node has no event of type `Create`.
The proposed changes address this situation in postponing the propagation creation of the local folder and all its descendants to the next synchronization. To this end, the local identifiers that are reused by the new items created locally are inserted into the ComputeFSOperationsWorker::_localReusedIds" and the `Create` operations detected on them or on any of their descendants are removed from the …
=> fix(compute-fs-operations): postpone the remote creation of newly created local items if they reuse the identifiers of deleted local items

.github/workflows/kdrive-desktop-release.yml
After this [PR](https://github.com/Infomaniak/desktop-kDrive/pull/948), the names of the release notes files do not refer to any release date anymore.
The proposed changes make sure that the CI script which uploads the release notes take this simplification into account.
=> feat(release-notes): decouple release notes from release date (CI upload script)

infomaniak-build-tools/conan/recipes/openssl/all/conanfile.py, infomaniak-build-tools/conan/recipes/openssl/all/openssl_build.sh, infomaniak-build-tools/conan/recipes/openssl/all/openssl_universal_build.sh
This PR modernizes and improves the reliability of the OpenSSL Conan recipe used in `infomaniak-build-tools` by replacing the old `openssl_universal_build.sh` script with a new, more explicit and robust `openssl_build.sh`.
- **Added zlib path handling** in the build command (`--zlib-include` / `--zlib-lib`), with explicit validation of zlib libraries presence.
- **Support for the `--version` parameter** to build the OpenSSL version declared in the Conan recipe.
- **Stronger validation in `validate()`**:
- Force the build to `Release`
- Warning if the `shared` option is disabled
- **Improved universal build**:
- Clean download and extraction of sources (via curl + tar) instead of git
- Separate builds for `x86_64` and `arm64`, then merge using `lipo`
- Correct install name definition and …
=> openssl conan recipe: refactor recipe and build script to support zlib and improve universal build

src/libsyncengine/jobs/network/kDrive_API/getfilelistjob.cpp, src/libsyncengine/jobs/network/kDrive_API/getfilelistjob.h, src/libsyncengine/jobs/network/kDrive_API/getrootfilelistjob.cpp, src/libsyncengine/jobs/network/kDrive_API/getrootfilelistjob.h, src/server/requests/serverrequests.cpp, test/libsyncengine/jobs/network/testnetworkjobs.cpp
When listing the items inside a directory for the tree view, we do not use pagination. Therefore, if there are more items in the directory than the limit (1'000), some items are missing in the tree view.
This PR activates the pagination and sends another request if there are more items to retrieve.
=> Use pagination in file listing request

src/libcommon/utility/utility.cpp, src/libcommon/utility/utility.h, src/libcommongui/logger.cpp, src/libcommonserver/io/iohelper.cpp, test/libcommonserver/io/testio.cpp
On the server component side, the value returned by`IoHelper::tempDirectoryPath` controls the location of:
- the kDrive server cache (subfolder of depth 1),
- the kDrive server logs (subfolder of depth 1),
- the temporary folder where the application is installed on Windows.
On the client component side, the logs are located inside `QDir::temp()` (subfolder of depth 1) which is also  the default value of `IoHelper::tempDirectoryPath`.
The proposed changes let the environment variable `KDRIVE_TMP_PATH` serve as the value returned by `IoHelper::tempDirectoryPath`, as well as the value of the parent directory of the client logs, provided this environment variable is set and non-empty.
The previous logic is left unchanged if  `KDRIVE_TMP_PATH` is not set with a non-empty value.
=> [TRELLO-1116] Allows users to set the kDrive temporary directory by means of the environment variable `KDRIVE_TMP_PATH`

src/libcommonserver/log/log.h, src/libcommonserver/utility/utility_win.cpp, test/libcommonserver/io/testchecksetgetrights.cpp, test/libcommonserver/utility/testutility.cpp, test/test_utility/testhelpers.h
This pull request follows-up with reported failures when moving items to trash that 
- do not raise any error,
- do not leave any trace in logs.
The proposed changes make sure the remaining possible errors are handled and their messages are logged.
=> [TRELLO-1107] Handle and log every error raised in `Utility::moveItemToTrash` (Windows)
