src/libcommon/keychainmanager/keychainmanager.cpp
src/libcommonserver/utility/utility.cpp
src/libcommonserver/utility/utility.h
src/libsyncengine/jobs/network/abstractnetworkjob.cpp
src/libsyncengine/jobs/network/abstractnetworkjob.h
src/libsyncengine/jobs/network/abstracttokennetworkjob.cpp
src/libsyncengine/jobs/network/login/abstractloginjob.cpp
src/libsyncengine/jobs/network/login/abstractloginjob.h
test/libparms/CMakeLists.txt

More log + sentry event added in case of login issue

KDESKTOP-643-Add-more-log-in-case-of-login-issue

---

src/gui/CMakeLists.txt
src/libcommonserver/CMakeLists.txt
test/libparms/CMakeLists.txt

KDESKTOP-667-Windows-build-broken

---

src/crashreporter/CMakeLists.txt

KDESKTOP-668 Fix Windows build

---

.github/workflows/linux.yml
infomaniak-build-tools/linux/build-ci-amd64.sh
infomaniak-build-tools/linux/build-ci.sh

Linux CI implementation
~~MR will be marked as ready for testing, please do not merge~~
CI runner was created and is operational

KDESKTOP-675-Linux-CI

---

infomaniak-build-tools/linux/Readme.md
infomaniak-build-tools/macos/Readme.md
infomaniak-build-tools/windows/Readme.md

Update OpenSSL and Poco version

KDESKTOP-673-Bump-poco

---

src/gui/appclient.cpp
src/gui/appclient.h
src/server/appserver.cpp
src/server/appserver.h
src/server/mainserver.cpp

Fix --synthesis and --settings launch options

KDESKTOP-740-Lauch-options-synthesis-and-settings-are-broken

---

infomaniak-build-tools/macos/Readme.md

Only update the documentation, changes must be done on everyone's computer

KDESKTOP-831-Update-Sparkle-because-of-important-security-fix

---

src/gui/genericerroritemwidget.cpp
src/gui/guiutility.cpp
src/gui/guiutility.h
src/gui/preferenceswidget.cpp
src/gui/synchronizeditemwidget.cpp
src/gui/synchronizeditemwidget.h

The date in the ErrorItemWidget was never translated

KDESKTOP-861-Errors-page-Date-format-always-EN

---

src/libcommonserver/vfs.h
src/libsyncengine/propagation/executor/executorworker.cpp
src/libsyncengine/syncpal/syncpal.cpp
src/libsyncengine/syncpal/syncpal.h
src/server/appserver.cpp
src/server/appserver.h
src/server/vfs/mac/litesyncextconnector.h
src/server/vfs/mac/litesyncextconnector.mm
src/server/vfs/mac/vfs_mac.cpp
src/server/vfs/mac/vfs_mac.h

Syncing a folder containg lots of items inside it took a lot of time because of the status update of the parent folder

KDESKTOP-875-Upload-of-big-folder-very-slow-with-LiteSync-activated

---

src/gui/appclient.cpp
src/gui/appclient.h

Closing the client, sometime popup a “Kdrive already running” window.

KDESKTOP-906-Self-restarter-sometimes-not-behave-as-expected

---

src/libcommonserver/io/iohelper.cpp
src/libsyncengine/syncpal/syncpalworker.cpp
src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp
src/libsyncengine/update_detection/file_system_observer/fsoperationset.cpp
src/libsyncengine/update_detection/file_system_observer/fsoperationset.h
src/libsyncengine/update_detection/file_system_observer/localfilesystemobserverworker.cpp

This PR aims to improve logs in order to have a better understanding of issues occuring in phase 2 (compute FS operations)

Kdesktop 916 add more log

---

src/libcommon/comm.h
src/libcommon/utility/utility.h
test/libcommon/utility/testutility.cpp
test/libcommon/utility/testutility.h

This pull request addresses [KDESKTOP-1039](https://infomaniak.atlassian.net/browse/KDESKTOP-1039).
[KDESKTOP-1039]: https://infomaniak.atlassian.net/browse/KDESKTOP-1039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[KDESKTOP-1039] Fixes and tests the ArgsWriter class

---

src/libsyncengine/propagation/executor/executorworker.cpp
src/server/socketlistener.cpp

The version `3.6.3 `introduces a crash when the user tries to upload a file over the max allowed size.

[KDESKTOP-1112] Fix issue with UploadSession of file over the size limit.

---

src/libsyncengine/login/login.cpp

Since we have access token with infinite lifetime now, we do not have refresh token anymore. Therefore, if the app receives a 401 error, for example after token revocation, it should not try to refresh the token (unless right after a migration, where we still have a refresh token). From now on, on error 401 reception, the app will ask the user to log in immediately.

KDESKTOP-1182-No-re-login-asked-if-the-token-has-been-revoked

---

src/libcommon/utility/types.cpp
src/libsyncengine/update_detection/file_system_observer/folderwatcher_mac.cpp

App is crashing in debug mode after duplicating a file from the Finder

KDESKTOP-1198-macOS-Crash-in-debug-mode

---

extensions/MacOSX/kDriveLiteSync/Extension/xpcService.m

Add new process to LiteSync exclusion list

KDESKTOP-1231 - Add process to LiteSync exclusion

---

src/libcommonserver/utility/utility_mac.mm
src/server/appserver.cpp

First ignore kDrive Finder extension, then activate it back

KDESKTOP-1243 - Ignore Finder extension first

---

src/libsyncengine/db/syncdb.cpp

This pull-request addresses [KDESKTOP-1268](https://infomaniak.atlassian.net/browse/KDESKTOP-1268).
[KDESKTOP-1268]: https://infomaniak.atlassian.net/browse/KDESKTOP-1268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixes the Sync databases for every version lower than 3.6.7

---

translations/client_de.ts

This is issue was reported by Simon Beier from our Support Team.

Fix German translation issue: Aktie -> Teilen (feedback from Support)

---

src/libsyncengine/progress/progressinfo.cpp
src/libsyncengine/progress/progressinfo.h
src/libsyncengine/progress/syncfileitem.h
src/libsyncengine/syncpal/syncpal.cpp
test/libsyncengine/syncpal/testsyncpal.cpp
test/libsyncengine/syncpal/testsyncpal.h

There is still an issue wioth NFD encoding in Executor

KDESKTOP-1305-File-path-not-found-in-Executor

---

src/libcommon/utility/types.cpp
src/libcommon/utility/types.h
src/libsyncengine/jobs/network/API_v2/abstracttokennetworkjob.cpp
src/libsyncengine/jobs/network/abstractnetworkjob.cpp
src/libsyncengine/requests/serverrequests.cpp
test/libsyncengine/requests/testserverrequests.cpp
test/libsyncengine/requests/testserverrequests.h

Fix regression on get file share link

KDESKTOP-1346-Fail-to-retrieve-the-public-share-link-on-2nd-call

---

infomaniak-build-tools/kDrive-template.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-linux-de.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-linux-en.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-linux-es.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-linux-fr.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-linux-it.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-macos-de.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-macos-en.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-macos-es.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-macos-fr.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-macos-it.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-win-de.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-win-en.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-win-es.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-win-fr.html
release_notes/kDrive-3.6.7.20241105/kDrive-3.6.7.20241105-win-it.html

Generate release notes for version 3.6.7

KDESKTOP-1345-Release-notes-3.6.7

---

infomaniak-build-tools/kDrive-template.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-linux-de.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-linux-en.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-linux-es.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-linux-fr.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-linux-it.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-macos-de.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-macos-en.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-macos-es.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-macos-fr.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-macos-it.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-win-de.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-win-en.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-win-es.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-win-fr.html
release_notes/kDrive-3.6.7.20241120/kDrive-3.6.7.20241120-win-it.html

KDESKTOP-1394-Minor-release-note-update

---

extensions/windows/cfapi/Common/debug.h
extensions/windows/cfapi/Common/utilities.h
extensions/windows/cfapi/Vfs/cloudproviderregistrar.cpp
src/server/vfs/win/debug.h
src/server/vfs/win/vfs_win.cpp

Not reproduced.
Checks added to avoid crash.

Windows - LitesSync - Crash when registering folder

---

src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.cpp
src/libsyncengine/update_detection/file_system_observer/computefsoperationworker.h
src/libsyncengine/update_detection/file_system_observer/folderwatcher_win.cpp
src/libsyncengine/update_detection/file_system_observer/snapshot/snapshot.cpp
src/libsyncengine/update_detection/file_system_observer/snapshot/snapshotitem.cpp
src/libsyncengine/update_detection/file_system_observer/snapshot/snapshotitem.h
test/libsyncengine/update_detection/file_system_observer/testsnapshot.cpp
test/libsyncengine/update_detection/file_system_observer/testsnapshot.h

Same as https://github.com/Infomaniak/desktop-kDrive/pull/479 but `develop`as base branch

Fix issue with folder name containing colon2

---

CMakeLists.txt
extensions/windows/cfapi/FileExplorerExtension/FileExplorerExtension.vcxproj
extensions/windows/cfapi/Vfs/Vfs.vcxproj
src/common/filesystembase.cpp
src/gui/CMakeLists.txt
src/gui/abstractfileitemwidget.cpp
src/gui/appclient.cpp
src/gui/fileitemwidget.cpp
src/libcommon/CMakeLists.txt
src/libcommon/log/sentry/handler.cpp
src/libcommongui/CMakeLists.txt
src/libcommonserver/CMakeLists.txt
src/libparms/CMakeLists.txt
src/libsyncengine/CMakeLists.txt
src/libsyncengine/jobs/network/API_v2/createdirjob.h
src/libsyncengine/jobs/network/API_v2/downloadjob.h
src/libsyncengine/jobs/network/API_v2/duplicatejob.h
src/libsyncengine/jobs/network/API_v2/movejob.h
src/libsyncengine/jobs/network/API_v2/renamejob.h
src/libsyncengine/jobs/network/API_v2/upload_session/uploadsessionfinishjob.h
src/libsyncengine/jobs/network/API_v2/uploadjob.h
src/libsyncengine/syncpal/conflictingfilescorrector.h
src/server/CMakeLists.txt
test/libcommon/CMakeLists.txt
test/libcommonserver/CMakeLists.txt
test/libparms/CMakeLists.txt
test/libsyncengine/CMakeLists.txt
test/mocks/libsyncengine/vfs/mockvfs.h
test/server/CMakeLists.txt

macOS: 2'41'' => 2'19''
Windows: 13'01'' => 6'10''
Linux: 4'47'' => 2'36''

Kdesktop 1562 use precompiled headers

---

src/libcommonserver/vfs/mac/vfs_mac.cpp

It was possible to dehydrate a file not yet synchronized by following those steps:
- Hydrate file “test.txt”
- Pause the sync
- Duplicate “test.txt” (into “test copy.txt”)
- Dehydrate “test copy.txt” from the Finder
- Start the sync

KDESKTOP-1559-Blacklisted-Dehydrating-a-newly-created-file

---

infomaniak-build-tools/linux/build-release-amd64-via-podman.sh
infomaniak-build-tools/linux/build-release-appimage-amd64.sh
infomaniak-build-tools/linux/build-release-appimage-arm64.sh
infomaniak-build-tools/linux/build-release-arm64-via-podman.sh

Linux version has a "master" suffix. This PR aims to uniformize the version string on every OS.

Uniformize version format

---

src/server/appserver.cpp

Add more log about the OS on application startup.

Log kernel type and version

---

.clang-format
src/libcommon/utility/types.h
src/libsyncengine/propagation/operation_sorter/operationsorterworker.cpp
src/libsyncengine/reconciliation/platform_inconsistency_checker/platforminconsistencycheckerutility.h
src/libsyncengine/reconciliation/syncoperation.cpp

Suggestions to make clang format more restrictive

Changes in clang format

---

src/gui/guiutility.cpp
src/libcommon/utility/utility.cpp
src/libcommon/utility/utility.h
test/libcommonserver/utility/testutility.cpp
test/libcommonserver/utility/testutility.h

Forbid to create sync a the root of a drive

Kdesktop 818 sync at the root of a drive not working with lite sync on

---

src/libsyncengine/propagation/executor/executorworker.cpp
src/libsyncengine/syncpal/operationprocessor.cpp
src/libsyncengine/update_detection/update_detector/node.h
src/libsyncengine/update_detection/update_detector/updatetreeworker.cpp
test/libsyncengine/propagation/operation_sorter/testoperationsorterworker.cpp
test/libsyncengine/reconciliation/conflict_finder/testconflictfinderworker.cpp
test/libsyncengine/reconciliation/operation_generator/testoperationgeneratorworker.cpp
test/libsyncengine/reconciliation/operation_generator/testoperationgeneratorworker.h
test/libsyncengine/syncpal/testoperationprocessor.cpp
test/libsyncengine/test.cpp
test/libsyncengine/update_detection/update_detector/testupdatetreeworker.cpp
test/test_classes/testsituationgenerator.cpp
test/test_classes/testsituationgenerator.h

Re-activate and refactor tests on `OperationGeneratorWorker`.

Refactor tests on OperationGeneratorWorker

---

CMakeLists.txt
src/gui/CMakeLists.txt
src/libcommon/CMakeLists.txt
src/libcommongui/CMakeLists.txt
src/libcommonserver/CMakeLists.txt
src/libparms/CMakeLists.txt
src/libsyncengine/CMakeLists.txt
src/server/CMakeLists.txt
test/libcommon/CMakeLists.txt
test/libcommonserver/CMakeLists.txt
test/libparms/CMakeLists.txt
test/libsyncengine/CMakeLists.txt
test/server/CMakeLists.txt

build: bump minimum required CMake version to 3.16

---

src/libsyncengine/jobs/network/API_v2/downloadjob.cpp
src/libsyncengine/jobs/network/API_v2/downloadjob.h
src/libsyncengine/reconciliation/operation_generator/operationgeneratorworker.cpp
src/libsyncengine/update_detection/file_system_observer/folderwatcher_linux.cpp
src/libsyncengine/update_detection/file_system_observer/folderwatcher_mac.cpp
src/libsyncengine/update_detection/file_system_observer/folderwatcher_win.cpp
src/server/appserver.cpp
test/libsyncengine/jobs/network/testnetworkjobs.cpp

This PR has 2 goals:
- Improve logging in the event of insufficient disk space (show the remaining available space).
- Remote delete operations should decrease the total estimated volume of data to be downloaded.

Improve disk size limit reached

---

src/gui4/windows/kDrive client/kDrive client/CustomControls/KSuiteUpgradeBar.xaml
src/gui4/windows/kDrive client/kDrive client/Styles/InfomaniakStyles.xaml

WinUI3 handle dark mode in ksuite bar
